<?php
/**
 * AccountUsage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI.
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpatioClient\Model;

use \ArrayAccess;
use \SpatioClient\ObjectSerializer;

/**
 * AccountUsage Class Doc Comment
 *
 * @category Class
 * @description Today&#39;s usage counters. Snapshot reflects the in-memory rollup; counts reset at UTC midnight.
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountUsage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AccountUsage';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'date' => 'string',
        'api_calls' => 'int',
        'email_sends' => 'int',
        'notes_count' => 'int',
        'sheets_count' => 'int',
        'slides_count' => 'int',
        'files_count' => 'int',
        'tasks_count' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'date' => null,
        'api_calls' => null,
        'email_sends' => null,
        'notes_count' => null,
        'sheets_count' => null,
        'slides_count' => null,
        'files_count' => null,
        'tasks_count' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'date' => false,
        'api_calls' => false,
        'email_sends' => false,
        'notes_count' => false,
        'sheets_count' => false,
        'slides_count' => false,
        'files_count' => false,
        'tasks_count' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date' => 'date',
        'api_calls' => 'api_calls',
        'email_sends' => 'email_sends',
        'notes_count' => 'notes_count',
        'sheets_count' => 'sheets_count',
        'slides_count' => 'slides_count',
        'files_count' => 'files_count',
        'tasks_count' => 'tasks_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date' => 'setDate',
        'api_calls' => 'setApiCalls',
        'email_sends' => 'setEmailSends',
        'notes_count' => 'setNotesCount',
        'sheets_count' => 'setSheetsCount',
        'slides_count' => 'setSlidesCount',
        'files_count' => 'setFilesCount',
        'tasks_count' => 'setTasksCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date' => 'getDate',
        'api_calls' => 'getApiCalls',
        'email_sends' => 'getEmailSends',
        'notes_count' => 'getNotesCount',
        'sheets_count' => 'getSheetsCount',
        'slides_count' => 'getSlidesCount',
        'files_count' => 'getFilesCount',
        'tasks_count' => 'getTasksCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('api_calls', $data ?? [], null);
        $this->setIfExists('email_sends', $data ?? [], null);
        $this->setIfExists('notes_count', $data ?? [], null);
        $this->setIfExists('sheets_count', $data ?? [], null);
        $this->setIfExists('slides_count', $data ?? [], null);
        $this->setIfExists('files_count', $data ?? [], null);
        $this->setIfExists('tasks_count', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date
     *
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string $date Always `today` for the current-day rollup.
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets api_calls
     *
     * @return int|null
     */
    public function getApiCalls()
    {
        return $this->container['api_calls'];
    }

    /**
     * Sets api_calls
     *
     * @param int|null $api_calls api_calls
     *
     * @return self
     */
    public function setApiCalls($api_calls)
    {
        if (is_null($api_calls)) {
            throw new \InvalidArgumentException('non-nullable api_calls cannot be null');
        }
        $this->container['api_calls'] = $api_calls;

        return $this;
    }

    /**
     * Gets email_sends
     *
     * @return int|null
     */
    public function getEmailSends()
    {
        return $this->container['email_sends'];
    }

    /**
     * Sets email_sends
     *
     * @param int|null $email_sends email_sends
     *
     * @return self
     */
    public function setEmailSends($email_sends)
    {
        if (is_null($email_sends)) {
            throw new \InvalidArgumentException('non-nullable email_sends cannot be null');
        }
        $this->container['email_sends'] = $email_sends;

        return $this;
    }

    /**
     * Gets notes_count
     *
     * @return int|null
     */
    public function getNotesCount()
    {
        return $this->container['notes_count'];
    }

    /**
     * Sets notes_count
     *
     * @param int|null $notes_count notes_count
     *
     * @return self
     */
    public function setNotesCount($notes_count)
    {
        if (is_null($notes_count)) {
            throw new \InvalidArgumentException('non-nullable notes_count cannot be null');
        }
        $this->container['notes_count'] = $notes_count;

        return $this;
    }

    /**
     * Gets sheets_count
     *
     * @return int|null
     */
    public function getSheetsCount()
    {
        return $this->container['sheets_count'];
    }

    /**
     * Sets sheets_count
     *
     * @param int|null $sheets_count sheets_count
     *
     * @return self
     */
    public function setSheetsCount($sheets_count)
    {
        if (is_null($sheets_count)) {
            throw new \InvalidArgumentException('non-nullable sheets_count cannot be null');
        }
        $this->container['sheets_count'] = $sheets_count;

        return $this;
    }

    /**
     * Gets slides_count
     *
     * @return int|null
     */
    public function getSlidesCount()
    {
        return $this->container['slides_count'];
    }

    /**
     * Sets slides_count
     *
     * @param int|null $slides_count slides_count
     *
     * @return self
     */
    public function setSlidesCount($slides_count)
    {
        if (is_null($slides_count)) {
            throw new \InvalidArgumentException('non-nullable slides_count cannot be null');
        }
        $this->container['slides_count'] = $slides_count;

        return $this;
    }

    /**
     * Gets files_count
     *
     * @return int|null
     */
    public function getFilesCount()
    {
        return $this->container['files_count'];
    }

    /**
     * Sets files_count
     *
     * @param int|null $files_count files_count
     *
     * @return self
     */
    public function setFilesCount($files_count)
    {
        if (is_null($files_count)) {
            throw new \InvalidArgumentException('non-nullable files_count cannot be null');
        }
        $this->container['files_count'] = $files_count;

        return $this;
    }

    /**
     * Gets tasks_count
     *
     * @return int|null
     */
    public function getTasksCount()
    {
        return $this->container['tasks_count'];
    }

    /**
     * Sets tasks_count
     *
     * @param int|null $tasks_count tasks_count
     *
     * @return self
     */
    public function setTasksCount($tasks_count)
    {
        if (is_null($tasks_count)) {
            throw new \InvalidArgumentException('non-nullable tasks_count cannot be null');
        }
        $this->container['tasks_count'] = $tasks_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


