<?php
/**
 * AccountTierDetails
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI.
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpatioClient\Model;

use \ArrayAccess;
use \SpatioClient\ObjectSerializer;

/**
 * AccountTierDetails Class Doc Comment
 *
 * @category Class
 * @description Per-tier capability + quota envelope. Numeric quotas use 0/-1 idioms; treat large negatives as \&quot;unlimited.\&quot;
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountTierDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AccountTierDetails';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'tier' => 'string',
        'daily_api_calls' => 'int',
        'max_connected_accounts' => 'int',
        'max_email_sends_per_day' => 'int',
        'max_notes' => 'int',
        'max_sheets' => 'int',
        'max_slides' => 'int',
        'max_files' => 'int',
        'max_tasks' => 'int',
        'max_team_members' => 'int',
        'max_workspaces' => 'int',
        'storage_gb' => 'int',
        'has_automations' => 'bool',
        'has_advanced_automations' => 'bool',
        'has_full_api_access' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'tier' => null,
        'daily_api_calls' => null,
        'max_connected_accounts' => null,
        'max_email_sends_per_day' => null,
        'max_notes' => null,
        'max_sheets' => null,
        'max_slides' => null,
        'max_files' => null,
        'max_tasks' => null,
        'max_team_members' => null,
        'max_workspaces' => null,
        'storage_gb' => null,
        'has_automations' => null,
        'has_advanced_automations' => null,
        'has_full_api_access' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'tier' => false,
        'daily_api_calls' => false,
        'max_connected_accounts' => false,
        'max_email_sends_per_day' => false,
        'max_notes' => false,
        'max_sheets' => false,
        'max_slides' => false,
        'max_files' => false,
        'max_tasks' => false,
        'max_team_members' => false,
        'max_workspaces' => false,
        'storage_gb' => false,
        'has_automations' => false,
        'has_advanced_automations' => false,
        'has_full_api_access' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tier' => 'tier',
        'daily_api_calls' => 'daily_api_calls',
        'max_connected_accounts' => 'max_connected_accounts',
        'max_email_sends_per_day' => 'max_email_sends_per_day',
        'max_notes' => 'max_notes',
        'max_sheets' => 'max_sheets',
        'max_slides' => 'max_slides',
        'max_files' => 'max_files',
        'max_tasks' => 'max_tasks',
        'max_team_members' => 'max_team_members',
        'max_workspaces' => 'max_workspaces',
        'storage_gb' => 'storage_gb',
        'has_automations' => 'has_automations',
        'has_advanced_automations' => 'has_advanced_automations',
        'has_full_api_access' => 'has_full_api_access'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tier' => 'setTier',
        'daily_api_calls' => 'setDailyApiCalls',
        'max_connected_accounts' => 'setMaxConnectedAccounts',
        'max_email_sends_per_day' => 'setMaxEmailSendsPerDay',
        'max_notes' => 'setMaxNotes',
        'max_sheets' => 'setMaxSheets',
        'max_slides' => 'setMaxSlides',
        'max_files' => 'setMaxFiles',
        'max_tasks' => 'setMaxTasks',
        'max_team_members' => 'setMaxTeamMembers',
        'max_workspaces' => 'setMaxWorkspaces',
        'storage_gb' => 'setStorageGb',
        'has_automations' => 'setHasAutomations',
        'has_advanced_automations' => 'setHasAdvancedAutomations',
        'has_full_api_access' => 'setHasFullApiAccess'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tier' => 'getTier',
        'daily_api_calls' => 'getDailyApiCalls',
        'max_connected_accounts' => 'getMaxConnectedAccounts',
        'max_email_sends_per_day' => 'getMaxEmailSendsPerDay',
        'max_notes' => 'getMaxNotes',
        'max_sheets' => 'getMaxSheets',
        'max_slides' => 'getMaxSlides',
        'max_files' => 'getMaxFiles',
        'max_tasks' => 'getMaxTasks',
        'max_team_members' => 'getMaxTeamMembers',
        'max_workspaces' => 'getMaxWorkspaces',
        'storage_gb' => 'getStorageGb',
        'has_automations' => 'getHasAutomations',
        'has_advanced_automations' => 'getHasAdvancedAutomations',
        'has_full_api_access' => 'getHasFullApiAccess'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tier', $data ?? [], null);
        $this->setIfExists('daily_api_calls', $data ?? [], null);
        $this->setIfExists('max_connected_accounts', $data ?? [], null);
        $this->setIfExists('max_email_sends_per_day', $data ?? [], null);
        $this->setIfExists('max_notes', $data ?? [], null);
        $this->setIfExists('max_sheets', $data ?? [], null);
        $this->setIfExists('max_slides', $data ?? [], null);
        $this->setIfExists('max_files', $data ?? [], null);
        $this->setIfExists('max_tasks', $data ?? [], null);
        $this->setIfExists('max_team_members', $data ?? [], null);
        $this->setIfExists('max_workspaces', $data ?? [], null);
        $this->setIfExists('storage_gb', $data ?? [], null);
        $this->setIfExists('has_automations', $data ?? [], null);
        $this->setIfExists('has_advanced_automations', $data ?? [], null);
        $this->setIfExists('has_full_api_access', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tier'] === null) {
            $invalidProperties[] = "'tier' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tier
     *
     * @return string
     */
    public function getTier()
    {
        return $this->container['tier'];
    }

    /**
     * Sets tier
     *
     * @param string $tier tier
     *
     * @return self
     */
    public function setTier($tier)
    {
        if (is_null($tier)) {
            throw new \InvalidArgumentException('non-nullable tier cannot be null');
        }
        $this->container['tier'] = $tier;

        return $this;
    }

    /**
     * Gets daily_api_calls
     *
     * @return int|null
     */
    public function getDailyApiCalls()
    {
        return $this->container['daily_api_calls'];
    }

    /**
     * Sets daily_api_calls
     *
     * @param int|null $daily_api_calls daily_api_calls
     *
     * @return self
     */
    public function setDailyApiCalls($daily_api_calls)
    {
        if (is_null($daily_api_calls)) {
            throw new \InvalidArgumentException('non-nullable daily_api_calls cannot be null');
        }
        $this->container['daily_api_calls'] = $daily_api_calls;

        return $this;
    }

    /**
     * Gets max_connected_accounts
     *
     * @return int|null
     */
    public function getMaxConnectedAccounts()
    {
        return $this->container['max_connected_accounts'];
    }

    /**
     * Sets max_connected_accounts
     *
     * @param int|null $max_connected_accounts max_connected_accounts
     *
     * @return self
     */
    public function setMaxConnectedAccounts($max_connected_accounts)
    {
        if (is_null($max_connected_accounts)) {
            throw new \InvalidArgumentException('non-nullable max_connected_accounts cannot be null');
        }
        $this->container['max_connected_accounts'] = $max_connected_accounts;

        return $this;
    }

    /**
     * Gets max_email_sends_per_day
     *
     * @return int|null
     */
    public function getMaxEmailSendsPerDay()
    {
        return $this->container['max_email_sends_per_day'];
    }

    /**
     * Sets max_email_sends_per_day
     *
     * @param int|null $max_email_sends_per_day max_email_sends_per_day
     *
     * @return self
     */
    public function setMaxEmailSendsPerDay($max_email_sends_per_day)
    {
        if (is_null($max_email_sends_per_day)) {
            throw new \InvalidArgumentException('non-nullable max_email_sends_per_day cannot be null');
        }
        $this->container['max_email_sends_per_day'] = $max_email_sends_per_day;

        return $this;
    }

    /**
     * Gets max_notes
     *
     * @return int|null
     */
    public function getMaxNotes()
    {
        return $this->container['max_notes'];
    }

    /**
     * Sets max_notes
     *
     * @param int|null $max_notes max_notes
     *
     * @return self
     */
    public function setMaxNotes($max_notes)
    {
        if (is_null($max_notes)) {
            throw new \InvalidArgumentException('non-nullable max_notes cannot be null');
        }
        $this->container['max_notes'] = $max_notes;

        return $this;
    }

    /**
     * Gets max_sheets
     *
     * @return int|null
     */
    public function getMaxSheets()
    {
        return $this->container['max_sheets'];
    }

    /**
     * Sets max_sheets
     *
     * @param int|null $max_sheets max_sheets
     *
     * @return self
     */
    public function setMaxSheets($max_sheets)
    {
        if (is_null($max_sheets)) {
            throw new \InvalidArgumentException('non-nullable max_sheets cannot be null');
        }
        $this->container['max_sheets'] = $max_sheets;

        return $this;
    }

    /**
     * Gets max_slides
     *
     * @return int|null
     */
    public function getMaxSlides()
    {
        return $this->container['max_slides'];
    }

    /**
     * Sets max_slides
     *
     * @param int|null $max_slides max_slides
     *
     * @return self
     */
    public function setMaxSlides($max_slides)
    {
        if (is_null($max_slides)) {
            throw new \InvalidArgumentException('non-nullable max_slides cannot be null');
        }
        $this->container['max_slides'] = $max_slides;

        return $this;
    }

    /**
     * Gets max_files
     *
     * @return int|null
     */
    public function getMaxFiles()
    {
        return $this->container['max_files'];
    }

    /**
     * Sets max_files
     *
     * @param int|null $max_files max_files
     *
     * @return self
     */
    public function setMaxFiles($max_files)
    {
        if (is_null($max_files)) {
            throw new \InvalidArgumentException('non-nullable max_files cannot be null');
        }
        $this->container['max_files'] = $max_files;

        return $this;
    }

    /**
     * Gets max_tasks
     *
     * @return int|null
     */
    public function getMaxTasks()
    {
        return $this->container['max_tasks'];
    }

    /**
     * Sets max_tasks
     *
     * @param int|null $max_tasks max_tasks
     *
     * @return self
     */
    public function setMaxTasks($max_tasks)
    {
        if (is_null($max_tasks)) {
            throw new \InvalidArgumentException('non-nullable max_tasks cannot be null');
        }
        $this->container['max_tasks'] = $max_tasks;

        return $this;
    }

    /**
     * Gets max_team_members
     *
     * @return int|null
     */
    public function getMaxTeamMembers()
    {
        return $this->container['max_team_members'];
    }

    /**
     * Sets max_team_members
     *
     * @param int|null $max_team_members max_team_members
     *
     * @return self
     */
    public function setMaxTeamMembers($max_team_members)
    {
        if (is_null($max_team_members)) {
            throw new \InvalidArgumentException('non-nullable max_team_members cannot be null');
        }
        $this->container['max_team_members'] = $max_team_members;

        return $this;
    }

    /**
     * Gets max_workspaces
     *
     * @return int|null
     */
    public function getMaxWorkspaces()
    {
        return $this->container['max_workspaces'];
    }

    /**
     * Sets max_workspaces
     *
     * @param int|null $max_workspaces max_workspaces
     *
     * @return self
     */
    public function setMaxWorkspaces($max_workspaces)
    {
        if (is_null($max_workspaces)) {
            throw new \InvalidArgumentException('non-nullable max_workspaces cannot be null');
        }
        $this->container['max_workspaces'] = $max_workspaces;

        return $this;
    }

    /**
     * Gets storage_gb
     *
     * @return int|null
     */
    public function getStorageGb()
    {
        return $this->container['storage_gb'];
    }

    /**
     * Sets storage_gb
     *
     * @param int|null $storage_gb storage_gb
     *
     * @return self
     */
    public function setStorageGb($storage_gb)
    {
        if (is_null($storage_gb)) {
            throw new \InvalidArgumentException('non-nullable storage_gb cannot be null');
        }
        $this->container['storage_gb'] = $storage_gb;

        return $this;
    }

    /**
     * Gets has_automations
     *
     * @return bool|null
     */
    public function getHasAutomations()
    {
        return $this->container['has_automations'];
    }

    /**
     * Sets has_automations
     *
     * @param bool|null $has_automations has_automations
     *
     * @return self
     */
    public function setHasAutomations($has_automations)
    {
        if (is_null($has_automations)) {
            throw new \InvalidArgumentException('non-nullable has_automations cannot be null');
        }
        $this->container['has_automations'] = $has_automations;

        return $this;
    }

    /**
     * Gets has_advanced_automations
     *
     * @return bool|null
     */
    public function getHasAdvancedAutomations()
    {
        return $this->container['has_advanced_automations'];
    }

    /**
     * Sets has_advanced_automations
     *
     * @param bool|null $has_advanced_automations has_advanced_automations
     *
     * @return self
     */
    public function setHasAdvancedAutomations($has_advanced_automations)
    {
        if (is_null($has_advanced_automations)) {
            throw new \InvalidArgumentException('non-nullable has_advanced_automations cannot be null');
        }
        $this->container['has_advanced_automations'] = $has_advanced_automations;

        return $this;
    }

    /**
     * Gets has_full_api_access
     *
     * @return bool|null
     */
    public function getHasFullApiAccess()
    {
        return $this->container['has_full_api_access'];
    }

    /**
     * Sets has_full_api_access
     *
     * @param bool|null $has_full_api_access has_full_api_access
     *
     * @return self
     */
    public function setHasFullApiAccess($has_full_api_access)
    {
        if (is_null($has_full_api_access)) {
            throw new \InvalidArgumentException('non-nullable has_full_api_access cannot be null');
        }
        $this->container['has_full_api_access'] = $has_full_api_access;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


