<?php
/**
 * CommitChunkedUploadResponse
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI.
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SpatioClient\Model;

use \ArrayAccess;
use \SpatioClient\ObjectSerializer;

/**
 * CommitChunkedUploadResponse Class Doc Comment
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CommitChunkedUploadResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CommitChunkedUploadResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'success' => 'bool',
        'file_id' => 'string',
        'manifest_id' => 'string',
        'version' => 'int',
        'total_size' => 'int',
        'physical_size' => 'int',
        'deduplication_pct' => 'float',
        'total_blocks' => 'int',
        'new_blocks' => 'int',
        'deduplicated_blocks' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'success' => null,
        'file_id' => null,
        'manifest_id' => null,
        'version' => null,
        'total_size' => 'int64',
        'physical_size' => 'int64',
        'deduplication_pct' => 'double',
        'total_blocks' => null,
        'new_blocks' => null,
        'deduplicated_blocks' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'success' => false,
        'file_id' => false,
        'manifest_id' => false,
        'version' => false,
        'total_size' => false,
        'physical_size' => false,
        'deduplication_pct' => false,
        'total_blocks' => false,
        'new_blocks' => false,
        'deduplicated_blocks' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'success' => 'success',
        'file_id' => 'fileId',
        'manifest_id' => 'manifestId',
        'version' => 'version',
        'total_size' => 'totalSize',
        'physical_size' => 'physicalSize',
        'deduplication_pct' => 'deduplicationPct',
        'total_blocks' => 'totalBlocks',
        'new_blocks' => 'newBlocks',
        'deduplicated_blocks' => 'deduplicatedBlocks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'success' => 'setSuccess',
        'file_id' => 'setFileId',
        'manifest_id' => 'setManifestId',
        'version' => 'setVersion',
        'total_size' => 'setTotalSize',
        'physical_size' => 'setPhysicalSize',
        'deduplication_pct' => 'setDeduplicationPct',
        'total_blocks' => 'setTotalBlocks',
        'new_blocks' => 'setNewBlocks',
        'deduplicated_blocks' => 'setDeduplicatedBlocks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'success' => 'getSuccess',
        'file_id' => 'getFileId',
        'manifest_id' => 'getManifestId',
        'version' => 'getVersion',
        'total_size' => 'getTotalSize',
        'physical_size' => 'getPhysicalSize',
        'deduplication_pct' => 'getDeduplicationPct',
        'total_blocks' => 'getTotalBlocks',
        'new_blocks' => 'getNewBlocks',
        'deduplicated_blocks' => 'getDeduplicatedBlocks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('success', $data ?? [], null);
        $this->setIfExists('file_id', $data ?? [], null);
        $this->setIfExists('manifest_id', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('total_size', $data ?? [], null);
        $this->setIfExists('physical_size', $data ?? [], null);
        $this->setIfExists('deduplication_pct', $data ?? [], null);
        $this->setIfExists('total_blocks', $data ?? [], null);
        $this->setIfExists('new_blocks', $data ?? [], null);
        $this->setIfExists('deduplicated_blocks', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['success'] === null) {
            $invalidProperties[] = "'success' can't be null";
        }
        if ($this->container['file_id'] === null) {
            $invalidProperties[] = "'file_id' can't be null";
        }
        if ($this->container['manifest_id'] === null) {
            $invalidProperties[] = "'manifest_id' can't be null";
        }
        if ($this->container['version'] === null) {
            $invalidProperties[] = "'version' can't be null";
        }
        if ($this->container['total_size'] === null) {
            $invalidProperties[] = "'total_size' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets success
     *
     * @return bool
     */
    public function getSuccess()
    {
        return $this->container['success'];
    }

    /**
     * Sets success
     *
     * @param bool $success success
     *
     * @return self
     */
    public function setSuccess($success)
    {
        if (is_null($success)) {
            throw new \InvalidArgumentException('non-nullable success cannot be null');
        }
        $this->container['success'] = $success;

        return $this;
    }

    /**
     * Gets file_id
     *
     * @return string
     */
    public function getFileId()
    {
        return $this->container['file_id'];
    }

    /**
     * Sets file_id
     *
     * @param string $file_id file_id
     *
     * @return self
     */
    public function setFileId($file_id)
    {
        if (is_null($file_id)) {
            throw new \InvalidArgumentException('non-nullable file_id cannot be null');
        }
        $this->container['file_id'] = $file_id;

        return $this;
    }

    /**
     * Gets manifest_id
     *
     * @return string
     */
    public function getManifestId()
    {
        return $this->container['manifest_id'];
    }

    /**
     * Sets manifest_id
     *
     * @param string $manifest_id manifest_id
     *
     * @return self
     */
    public function setManifestId($manifest_id)
    {
        if (is_null($manifest_id)) {
            throw new \InvalidArgumentException('non-nullable manifest_id cannot be null');
        }
        $this->container['manifest_id'] = $manifest_id;

        return $this;
    }

    /**
     * Gets version
     *
     * @return int
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param int $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets total_size
     *
     * @return int
     */
    public function getTotalSize()
    {
        return $this->container['total_size'];
    }

    /**
     * Sets total_size
     *
     * @param int $total_size total_size
     *
     * @return self
     */
    public function setTotalSize($total_size)
    {
        if (is_null($total_size)) {
            throw new \InvalidArgumentException('non-nullable total_size cannot be null');
        }
        $this->container['total_size'] = $total_size;

        return $this;
    }

    /**
     * Gets physical_size
     *
     * @return int|null
     */
    public function getPhysicalSize()
    {
        return $this->container['physical_size'];
    }

    /**
     * Sets physical_size
     *
     * @param int|null $physical_size physical_size
     *
     * @return self
     */
    public function setPhysicalSize($physical_size)
    {
        if (is_null($physical_size)) {
            throw new \InvalidArgumentException('non-nullable physical_size cannot be null');
        }
        $this->container['physical_size'] = $physical_size;

        return $this;
    }

    /**
     * Gets deduplication_pct
     *
     * @return float|null
     */
    public function getDeduplicationPct()
    {
        return $this->container['deduplication_pct'];
    }

    /**
     * Sets deduplication_pct
     *
     * @param float|null $deduplication_pct deduplication_pct
     *
     * @return self
     */
    public function setDeduplicationPct($deduplication_pct)
    {
        if (is_null($deduplication_pct)) {
            throw new \InvalidArgumentException('non-nullable deduplication_pct cannot be null');
        }
        $this->container['deduplication_pct'] = $deduplication_pct;

        return $this;
    }

    /**
     * Gets total_blocks
     *
     * @return int|null
     */
    public function getTotalBlocks()
    {
        return $this->container['total_blocks'];
    }

    /**
     * Sets total_blocks
     *
     * @param int|null $total_blocks total_blocks
     *
     * @return self
     */
    public function setTotalBlocks($total_blocks)
    {
        if (is_null($total_blocks)) {
            throw new \InvalidArgumentException('non-nullable total_blocks cannot be null');
        }
        $this->container['total_blocks'] = $total_blocks;

        return $this;
    }

    /**
     * Gets new_blocks
     *
     * @return int|null
     */
    public function getNewBlocks()
    {
        return $this->container['new_blocks'];
    }

    /**
     * Sets new_blocks
     *
     * @param int|null $new_blocks new_blocks
     *
     * @return self
     */
    public function setNewBlocks($new_blocks)
    {
        if (is_null($new_blocks)) {
            throw new \InvalidArgumentException('non-nullable new_blocks cannot be null');
        }
        $this->container['new_blocks'] = $new_blocks;

        return $this;
    }

    /**
     * Gets deduplicated_blocks
     *
     * @return int|null
     */
    public function getDeduplicatedBlocks()
    {
        return $this->container['deduplicated_blocks'];
    }

    /**
     * Sets deduplicated_blocks
     *
     * @param int|null $deduplicated_blocks deduplicated_blocks
     *
     * @return self
     */
    public function setDeduplicatedBlocks($deduplicated_blocks)
    {
        if (is_null($deduplicated_blocks)) {
            throw new \InvalidArgumentException('non-nullable deduplicated_blocks cannot be null');
        }
        $this->container['deduplicated_blocks'] = $deduplicated_blocks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


