<?php
/**
 * OrganizationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI.
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpatioClient\Test\Api;

use \SpatioClient\Configuration;
use \SpatioClient\ApiException;
use \SpatioClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for acceptOrganizationInvitation
     *
     * Accept an invitation to this organization..
     *
     */
    public function testAcceptOrganizationInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addOrganizationMember
     *
     * Add a member directly (skips invitation flow)..
     *
     */
    public function testAddOrganizationMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganization
     *
     * Create an organization..
     *
     */
    public function testCreateOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganizationConcept
     *
     * Create an org-brain concept (admin+ only)..
     *
     */
    public function testCreateOrganizationConcept()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganizationCustomRole
     *
     * Create a custom role (admin+ only)..
     *
     */
    public function testCreateOrganizationCustomRole()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganizationInvitation
     *
     * Invite a user to the organization..
     *
     */
    public function testCreateOrganizationInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOrganizationWorkspace
     *
     * Create a workspace inside an organization..
     *
     */
    public function testCreateOrganizationWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganization
     *
     * Delete an organization..
     *
     */
    public function testDeleteOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationConcept
     *
     * Delete a concept (admin+ only)..
     *
     */
    public function testDeleteOrganizationConcept()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationCustomRole
     *
     * Delete a custom role (admin+ only)..
     *
     */
    public function testDeleteOrganizationCustomRole()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOrganizationLogo
     *
     * Delete the organization logo..
     *
     */
    public function testDeleteOrganizationLogo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganization
     *
     * Fetch a single organization..
     *
     */
    public function testGetOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOrganizationConcept
     *
     * Fetch a concept..
     *
     */
    public function testGetOrganizationConcept()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMyOrganizations
     *
     * List the caller's organizations..
     *
     */
    public function testListMyOrganizations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationAuditLog
     *
     * Read the organization audit log (admin / billing-admin only)..
     *
     */
    public function testListOrganizationAuditLog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationConcepts
     *
     * List org-brain concepts (curated knowledge surfaced to agents)..
     *
     */
    public function testListOrganizationConcepts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationCustomRoles
     *
     * List custom roles defined on the organization..
     *
     */
    public function testListOrganizationCustomRoles()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationInvitations
     *
     * List pending invitations for an organization..
     *
     */
    public function testListOrganizationInvitations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationMembers
     *
     * List members of an organization..
     *
     */
    public function testListOrganizationMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listOrganizationWorkspaces
     *
     * List workspaces in an organization..
     *
     */
    public function testListOrganizationWorkspaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeOrganizationMember
     *
     * Remove a member from the organization..
     *
     */
    public function testRemoveOrganizationMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resendOrganizationInvitation
     *
     * Revoke and reissue an invitation with a fresh token..
     *
     */
    public function testResendOrganizationInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeOrganizationInvitation
     *
     * Revoke a pending invitation..
     *
     */
    public function testRevokeOrganizationInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganization
     *
     * Update organization metadata..
     *
     */
    public function testUpdateOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationConcept
     *
     * Update a concept (admin+ only)..
     *
     */
    public function testUpdateOrganizationConcept()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationCustomRole
     *
     * Update a custom role (admin+ only)..
     *
     */
    public function testUpdateOrganizationCustomRole()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOrganizationMember
     *
     * Update a member's role..
     *
     */
    public function testUpdateOrganizationMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadOrganizationLogo
     *
     * Upload (or replace) the organization logo. Multipart..
     *
     */
    public function testUploadOrganizationLogo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
