<?php
/**
 * RepoApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI.
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpatioClient\Test\Api;

use \SpatioClient\Configuration;
use \SpatioClient\ApiException;
use \SpatioClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * RepoApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RepoApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createRepoBranch
     *
     * Create a branch (from a base sha)..
     *
     */
    public function testCreateRepoBranch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRepoPullRequest
     *
     * Open a pull request..
     *
     */
    public function testCreateRepoPullRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRepoRepository
     *
     * Create a repository..
     *
     */
    public function testCreateRepoRepository()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRepoCommit
     *
     * Fetch a single commit..
     *
     */
    public function testGetRepoCommit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRepoRepository
     *
     * Fetch a single repository..
     *
     */
    public function testGetRepoRepository()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for linkRepoTask
     *
     * Link an existing Spatio task to this repo, allocating a per-repo number..
     *
     */
    public function testLinkRepoTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRepoBranches
     *
     * List branches on a repository..
     *
     */
    public function testListRepoBranches()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRepoCommits
     *
     * List commits on a repository..
     *
     */
    public function testListRepoCommits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRepoPullRequests
     *
     * List pull requests on a repository..
     *
     */
    public function testListRepoPullRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRepoRepositories
     *
     * List the caller's accessible repositories..
     *
     */
    public function testListRepoRepositories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRepoTasks
     *
     * List tasks linked to this repo (the \"issues\" surface)..
     *
     */
    public function testListRepoTasks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listRepoWorkflows
     *
     * List CI workflows..
     *
     */
    public function testListRepoWorkflows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mergeRepoPullRequest
     *
     * Merge a pull request..
     *
     */
    public function testMergeRepoPullRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for triggerRepoWorkflow
     *
     * Trigger a workflow_dispatch run..
     *
     */
    public function testTriggerRepoWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceCreateRepoBranch
     *
     * .
     *
     */
    public function testWorkspaceCreateRepoBranch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceCreateRepoPullRequest
     *
     * .
     *
     */
    public function testWorkspaceCreateRepoPullRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceCreateRepoRepository
     *
     * .
     *
     */
    public function testWorkspaceCreateRepoRepository()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceGetRepoCommit
     *
     * .
     *
     */
    public function testWorkspaceGetRepoCommit()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceGetRepoRepository
     *
     * .
     *
     */
    public function testWorkspaceGetRepoRepository()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceLinkRepoTask
     *
     * .
     *
     */
    public function testWorkspaceLinkRepoTask()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceListRepoBranches
     *
     * .
     *
     */
    public function testWorkspaceListRepoBranches()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceListRepoCommits
     *
     * .
     *
     */
    public function testWorkspaceListRepoCommits()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceListRepoPullRequests
     *
     * .
     *
     */
    public function testWorkspaceListRepoPullRequests()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceListRepoRepositories
     *
     * .
     *
     */
    public function testWorkspaceListRepoRepositories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceListRepoTasks
     *
     * .
     *
     */
    public function testWorkspaceListRepoTasks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceListRepoWorkflows
     *
     * .
     *
     */
    public function testWorkspaceListRepoWorkflows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceMergeRepoPullRequest
     *
     * .
     *
     */
    public function testWorkspaceMergeRepoPullRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for workspaceTriggerRepoWorkflow
     *
     * .
     *
     */
    public function testWorkspaceTriggerRepoWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
