<?php
/**
 * WorkspacesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SpatioAPI
 *
 * The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI.
 *
 * The version of the OpenAPI document: v1
 * Contact: hello@spatio.app
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SpatioClient\Test\Api;

use \SpatioClient\Configuration;
use \SpatioClient\ApiException;
use \SpatioClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkspacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  SpatioClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkspacesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for acceptWorkspaceInvitation
     *
     * Accept a workspace invitation by token. The signed-in user's email must match the invitation. Organization-token accept lives at `POST /v1/organizations/{org}/accept-invitation`..
     *
     */
    public function testAcceptWorkspaceInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addWorkspaceMember
     *
     * Add a member directly (skips invitation flow)..
     *
     */
    public function testAddWorkspaceMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWorkspace
     *
     * Create a workspace. Requires `organizationId` in the body — bare \"personal\" workspaces aren't supported on the public API..
     *
     */
    public function testCreateWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWorkspaceInvitation
     *
     * Invite a user to a workspace..
     *
     */
    public function testCreateWorkspaceInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPublicInvitation
     *
     * Fetch invitation details by token (unauthenticated). Used by the renderer to show invitation context before the user signs in..
     *
     */
    public function testGetPublicInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWorkspace
     *
     * Fetch a single workspace by id..
     *
     */
    public function testGetWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMyWorkspaces
     *
     * List the caller's workspaces (across organizations)..
     *
     */
    public function testListMyWorkspaces()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWorkspaceInvitations
     *
     * List pending workspace invitations..
     *
     */
    public function testListWorkspaceInvitations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listWorkspaceMembers
     *
     * List members of a workspace..
     *
     */
    public function testListWorkspaceMembers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeWorkspaceMember
     *
     * Remove a member from the workspace..
     *
     */
    public function testRemoveWorkspaceMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeWorkspaceInvitation
     *
     * Revoke a pending workspace invitation..
     *
     */
    public function testRevokeWorkspaceInvitation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWorkspace
     *
     * Update workspace metadata..
     *
     */
    public function testUpdateWorkspace()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWorkspaceMember
     *
     * Update a member's role..
     *
     */
    public function testUpdateWorkspaceMember()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
